### ISSUE TITLE
Feature set: Non-response options

### ISSUE THREAD

**Issue by eliza411** [storymachine/storymachine#1]
Feature: Non-response options
When I'm answering questions about a story if the responses I'm provided don't fit, 
I want a way to say so because it's frustrating to be have to say things I don't mean.

Scenario: Fixed responses
Given a narrator, a story, and a fixed set of responses
When none of the choices apply
I'd like to be able to indicate why

Examples:
| Not applicable    |
| Prefer not to say |
| Don't know        |
| Other             |

Scenario: Other text
Given a narrator, a story, and a fixed response question
When I choose Other
I'd like the option to enter my own response

Feature: Creating fixed-response questions
When I'm designing story questions, I want include non-response options and be able to tailor their labels to fit the intent of the question because these can tell me as much as the content answers and by making it easier for the narrator to express non-responses, I can trust actual responses more.

Scenario: Default labels
Given a project, a story survey, and a fixed-response question
When I add non-response options
The default labels should be "Not applicable, Prefer not to say, Don't know, and Other"
And Other should allow the text to be entered

Scenario: Customized lables
Given a project, a story survey, and a fixed-response question
When I add non-response options
I should be able to customize the default labels

Scenario: Customize number of options
Given a project, a story survey, and a fixed-response question
When I add non-response options
And add or remove response options

**Comment by lotyrin** [comment]
Depends on #67

**Comment by lotyrin** [comment]
I'm going to break the non-response and "other" into separate features, try to make the separation between what the project user and participant want from this clear, if I can.
