### ISSUE TITLE
Add ability to add questions after a story has been entered

### ISSUE THREAD

**Issue by eliza411** [storymachine/storymachine#112]
I created a story, added some questions, and edited the story in hopes of answering those questions but they don't appear. 

It's probable, especially in the early phases, that a question might need to be added after stories have already been entered, and it would be helpful for development, too.  Even mid-project, it's possible that a field would get added.

**Comment by lotyrin** [comment]
We certainly have some defects in different situations involving synchronization between stories, questions and answers.
