### ISSUE TITLE
Discuss required fields

### ISSUE THREAD

**Issue by eliza411** [storymachine/storymachine#114]
Right now, it appears that every field is required, which is probably fine. It's very possible that a field required of a user won't be required for the data entry person and it's possible that a field won't be required.

It makes sense from a workflow perspective to make questions required by default and allow the question creator to indicate when a field is optional. e.g., [  ] Optional  OR [ x ] Required or something like that.

**Comment by lotyrin** [comment]
We can have our validations take a story's state into account, to allow for draft states that get saved and remembered (especially for pagination) but still have strong requirements for finalized stories.
