### ISSUE TITLE
Feature: Create a project

### ISSUE THREAD

**Issue by eliza411** [storymachine/storymachine#5]
I want to be able to create a project that has narrators and editors, project information, a place for stories and a survey with questions about the stories which can have at least two forms, one designed for direct  collection and the other designed to facilitate data entry from paper surveys. Each entry form should be able to load and edit the information from the others. The default display of each survey question should match the data entry (except for not being editable). 

There should be:
Checkbox
Radio button
Short answer (textfield)
Long answer (text area) 
Sliders

**Comment by lotyrin** [comment]
Moving question/answer bits to #9
