### ISSUE TITLE
Participant user invitation

### ISSUE THREAD

**Issue by lotyrin** [storymachine/storymachine#6]
When a project owner adds a participant on a project that doesn't already have an account, we should send a nice introductory email inviting them to create their account and start contributing stories.

**Comment by eliza411** [comment]
There will be a point where the project owner may not be inviting a participant by e-mail. Instead, they'd have a URL up for some amount of time and they communicate a general URL. Imagine a presentation followed by a URL and call to action where the minimum barrier to entry is essential. The project would essentially allow the user to enter without *feeling* like they've entered an account. They'd enter stories, answer questions, and when they truly are ready to submit, they'd be offered a random ID and Pass, optionally connected to their e-mail, should they which to return and add more, etc.

**Comment by lotyrin** [comment]
I anticipated that option, but wasn't sure how important/likely it was vs. the model where participants have onymous accounts (and might also be project owners/team members). Do you see the invitation URL style to be significantly more important to the degree that it should be implemented first? Is the multi-role user rare enough that they we'll simplify and make them deal with the switch of modes between "I'm logged in with an account, managing projects" and "I'm in a temporary session from a link, participating in a project"?

**Comment by eliza411** [comment]
This probably warrants a conversation ... 

It's a question of how safe people feel to disclose risky stuff. For the DevOps project, sending an invite to an e-mail completely works. I would want to separate that from any record on the server, even so. (Essentially, if data unapproved for sharing were hacked, I'd not want any way to link a story to the participant). That clearly wouldn't prevent an investigation from discovering connections but it seems like reasonable precaution. So really, I think I am saying that an invite URL is more important.  

Thursday I can show you what I put together and what I was thinking at the time, if you want.
