### ISSUE TITLE
User profile wireframe

### ISSUE THREAD

**Issue by ActualAbby** [storymachine/storymachine#82]
![user_profile](https://cloud.githubusercontent.com/assets/6440363/7598064/c601bf4c-f8ac-11e4-9dcd-a8472b1a5ad4.png)

**Comment by lotyrin** [comment]
Is there a reason the existing email has its own form field?

We probably want action words on these submit buttons to distinguish them verbally as well as spacially from eachother.

**Comment by ActualAbby** [comment]
@lotyrin Updated

**Comment by lotyrin** [comment]
:+1:
