### ISSUE TITLE
Login Wireframe

### ISSUE THREAD

**Issue by ActualAbby** [storymachine/storymachine#83]
![login](https://cloud.githubusercontent.com/assets/6440363/7598215/b2f67cf2-f8ad-11e4-8ae4-16cd67602f48.png)

**Comment by lotyrin** [comment]
This register link should have a matching story.

We can't reset people's emails. If they lose their password and access to their email inbox both, we can't distinguish them from someone that's simply not them.

The language for the password recovery link should match what we have in the password recovery feature and be more semantic (we aren't linking them to something called "password", so the link text shouldn't just be "password")

**Comment by ActualAbby** [comment]
@lotyrin Updated and I will be doing a story pass to adjust things
