### ISSUE TITLE
Password Recovery Wireframe

### ISSUE THREAD

**Issue by ActualAbby** [storymachine/storymachine#85]
![password_recovery_lorem](https://cloud.githubusercontent.com/assets/6440363/7598693/1e9c75da-f8b1-11e4-9f5e-89a08a950ad2.png)

**Comment by lotyrin** [comment]
If we want this text here, lets cover it with a story. "I should see a message explaining how password recovery works". I think it can be simpler. Probably just "Submit your email address and we will send you a link so you can log in and set a new password."

**Comment by lotyrin** [comment]
Lets not put the actual text for these in here as well (just "Password reset explanation lorem ipsum..." or something) so we don't have you re-baking new PNGs repeatedly if we end up in back-and-forth about language.

**Comment by ActualAbby** [comment]
@lotyrin changed to lorem ipsum

**Comment by lotyrin** [comment]
:+1:
